#!/usr/bin/with-contenv bash
USER_NAME=${USER_NAME:-openssh}
USER_UID=${USER_UID:-2222}
USER_GID=${USER_GID:-2222}
USER_HOME_DIR="/home/${USER_NAME}"
USER_SSH_DIR="${USER_HOME_DIR}/.ssh"
USER_SSH_AUTHORIZED_KEYS_FILE="${USER_SSH_DIR}/authorized_keys"